// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgjevvjzgmqtlomcppiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnamV2dmp6Z21xdGxvbWNwcGl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMjQ4ODIsImV4cCI6MjA3MjgwMDg4Mn0.8R9KxyDj5B-DNzrXBGmsNwIUFN7_RW9L9mQcCie2hKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});